AspNetViewsCodeReuseExamples/Models/User.cs
using System;

namespace AspNetViewsCodeReuseExamples.Models
{
    public class User
    {
        public string Name { get; set; }

        public string Surname { get; set; }

        public DateTime Birthday { get; set; }
    }
}

AspNetViewsCodeReuseExamples/ViewModels/ChildActionViewModel.cs
namespace AspNetViewsCodeReuseExamples.ViewModels
{
    public class ChildActionViewModel
    {
        public string Query { get; set; }
    }
}

AspNetViewsCodeReuseExamples/ViewModels/DisplayEditorTemplatesViewModel.cs
using AspNetViewsCodeReuseExamples.IdmbComponent;
using AspNetViewsCodeReuseExamples.Models;

namespace AspNetViewsCodeReuseExamples.ViewModels
{
    public class DisplayEditorTemplatesViewModel
    {
        public DisplayEditorTemplatesViewModel()
        {
            User = new User();
        }

        public bool AreYouOk { get; set; }
        public User User { get; set; }
        public Movie Movie { get; set; }
        public Movie SpecialMovie { get; set; }
    }
}

AspNetViewsCodeReuseExamples/ViewModels/HtmlHelperViewModel.cs
using System.Collections;

namespace AspNetViewsCodeReuseExamples.ViewModels
{
    public class HtmlHelperViewModel
    {
        public IEnumerable Planets { get; set; }
    }
}

AspNetViewsCodeReuseExamples/ViewModels/PartialViewsViewModel.cs
using AspNetViewsCodeReuseExamples.Models;

namespace AspNetViewsCodeReuseExamples.ViewModels
{
    public class PartialViewsViewModel
    {
        public bool IsSpecialUser { get; set; }
        public User User { get; set; }
    }
}

AspNetViewsCodeReuseExamples/ViewModels/RazorHelpersViewModel.cs
using System.Collections.Generic;
using AspNetViewsCodeReuseExamples.Models;

namespace AspNetViewsCodeReuseExamples.ViewModels
{
    public class RazorHelpersViewModel
    {
        public List<User> Users { get; set; }
    }
}

AspNetViewsCodeReuseExamples/ViewModels/SearchMovieResultsViewModel.cs
using System.Collections.Generic;
using AspNetViewsCodeReuseExamples.IdmbComponent;

namespace AspNetViewsCodeReuseExamples.ViewModels
{
    public class SearchMovieResultsViewModel
    {
        public SearchMovieResultsViewModel(string query, List<Movie> movies)
        {
            Query = query;
            Movies = movies;
        }

        public string Query { get; private set; }
        public List<Movie> Movies { get; private set; }
    }
}

AspNetViewsCodeReuseExamples/Controllers/ChildActionController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AspNetViewsCodeReuseExamples.IdmbComponent;
using AspNetViewsCodeReuseExamples.ViewModels;

namespace AspNetViewsCodeReuseExamples.Controllers
{
    public class ChildActionController : Controller
    {
        public ActionResult Index(string query = null)
        {
            return View(new ChildActionViewModel { Query = query });
        }
        
        [ChildActionOnly]
        public ActionResult SearchMovies(string query)
        {
            List<Movie> movies = null;
            if (!string.IsNullOrWhiteSpace(query))
            {
                try
                {
                    movies = new MovieSearch().SearchPopular(query);
                }
                catch
                {
                    // For purposes of this sample app just assume there is no results :D
                }
            }

            // Return PartialView instead of View to ignore default view layout.
            return PartialView(new SearchMovieResultsViewModel(query, movies));
        }
    }
}

AspNetViewsCodeReuseExamples/Controllers/DisplayEditorTemplatesController.cs
using System;
using System.Web.Mvc;
using AspNetViewsCodeReuseExamples.IdmbComponent;
using AspNetViewsCodeReuseExamples.Models;
using AspNetViewsCodeReuseExamples.ViewModels;

namespace AspNetViewsCodeReuseExamples.Controllers
{
    public class DisplayEditorTemplatesController : Controller
    {
        private const string DisplayEditorTemplatesViewModelSessionKey = "DisplayEditorTemplatesViewModel";
        
        public ActionResult Index()
        {
            return RedirectToAction("DisplayTemplates");
        }

        public ActionResult DisplayTemplates()
        {
            var model = GetOrCreateDefaultDisplayEditorTemplatesViewModel();

            return View(model);
        }

        [HttpGet]
        public ActionResult EditorTemplates()
        {
            var model = GetOrCreateDefaultDisplayEditorTemplatesViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult EditorTemplates(DisplayEditorTemplatesViewModel model)
        {
            Session[DisplayEditorTemplatesViewModelSessionKey] = model;
            return RedirectToAction("DisplayTemplates");
        }

        private DisplayEditorTemplatesViewModel GetOrCreateDefaultDisplayEditorTemplatesViewModel()
        {
            var model = Session[DisplayEditorTemplatesViewModelSessionKey] as DisplayEditorTemplatesViewModel;

            if (model == null)
            {
                model = new DisplayEditorTemplatesViewModel
                {
                    AreYouOk = false,
                    User = new User { Name = "John", Surname = "Schmidt", Birthday = new DateTime(1975, 03, 08) },
                    Movie = new Movie { Title = "The Fast and the Furious", Description = "Los Angeles police officer Brian O'Connor must decide where his loyalties really lie when he becomes enamored with the street racing world he has been sent undercover to destroy." },
                    SpecialMovie = new Movie { Title = "Special", Description = "A lonely metermaid has a psychotic reaction to his medication and becomes convinced he's a superhero. A very select group of people in life are truly gifted. Special is a movie about everyone else."}
                };

                Session[DisplayEditorTemplatesViewModelSessionKey] = model;
            }

            return model;
        }
    }
}

AspNetViewsCodeReuseExamples/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AspNetViewsCodeReuseExamples.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

AspNetViewsCodeReuseExamples/Controllers/HtmlHelperController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AspNetViewsCodeReuseExamples.ViewModels;

namespace AspNetViewsCodeReuseExamples.Controllers
{
    public class HtmlHelperController : Controller
    {
        public ActionResult Index()
        {
            var model = new HtmlHelperViewModel
            {
                Planets = new List<string> { "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune" }
            };

            return View(model);
        }

    }
}

AspNetViewsCodeReuseExamples/Controllers/LayoutsController.cs
using System.Web.Mvc;

namespace AspNetViewsCodeReuseExamples.Controllers
{
    public class LayoutsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Nested()
        {
            return View();
        }
    }
}

AspNetViewsCodeReuseExamples/Controllers/PartialViewsController.cs
using System;
using System.Web.Mvc;
using AspNetViewsCodeReuseExamples.Models;
using AspNetViewsCodeReuseExamples.ViewModels;

namespace AspNetViewsCodeReuseExamples.Controllers
{
    public class PartialViewsController : Controller
    {
        public ActionResult Index()
        {
            var model = new PartialViewsViewModel
            {
                IsSpecialUser = true,
                User = new User { Name = "Thomas", Surname = "Edison", Birthday = new DateTime(1847, 02, 11) }
            };

            return View(model);
        }

    }
}

AspNetViewsCodeReuseExamples/Controllers/RazorHelpersController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AspNetViewsCodeReuseExamples.Models;
using AspNetViewsCodeReuseExamples.ViewModels;

namespace AspNetViewsCodeReuseExamples.Controllers
{
    public class RazorHelpersController : Controller
    {
        public ActionResult Index()
        {
            var model = new RazorHelpersViewModel
            {
                Users = new List<User> {
                    new User { Name = "Barbara", Birthday = new DateTime(2001, 04, 28) },
                    new User { Name = "Thomas", Surname = "Edison", Birthday = new DateTime(1847, 02, 11) },
                    new User { Birthday = new DateTime(1987, 05, 25) }
                }
            };

            return View(model);
        }

    }
}

AspNetViewsCodeReuseExamples/Views/ChildAction/Index.cshtml
@model dynamic

<h1>Child action example</h1>

<div>
    @using (Html.BeginForm("Index", "ChildAction", FormMethod.Get))
    {
        <span>Search movies: </span>
        <input type="text" name="query" />
        <input type="submit" value="Search" />
    }
</div>

<div>
    @Html.Action("SearchMovies", "ChildAction", new { query = Model.Query })
</div>

AspNetViewsCodeReuseExamples/Views/ChildAction/SearchMovies.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.SearchMovieResultsViewModel

<h2>Search result for query: "@Model.Query "</h2>

@if (string.IsNullOrWhiteSpace(Model.Query) || Model.Movies == null || !Model.Movies.Any())
{
    <span>No results</span>
}
else
{
    <ul>
        @foreach (var movie in Model.Movies)
        {
            <li>@movie.Title - @movie.Description</li>
        }
    </ul>
}

AspNetViewsCodeReuseExamples/Views/DisplayEditorTemplates/DisplayTemplates.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.DisplayEditorTemplatesViewModel


<h1>Display templates examples</h1>

<h2>Display template for Boolean</h2>
@Html.DisplayFor(m => m.AreYouOk)

<h2>Display template for User class</h2>
@Html.DisplayFor(m => m.User)

<h2>Local default display template for Movie class</h2>
@Html.DisplayFor(m => m.Movie)

<h2>Local not default display template for Movie class</h2>
@Html.DisplayFor(m => m.SpecialMovie, "SpecialMovie")

AspNetViewsCodeReuseExamples/Views/DisplayEditorTemplates/DisplayTemplates/Movie.cshtml
@model AspNetViewsCodeReuseExamples.IdmbComponent.Movie

<div class="movieContainer">
    <div class="movieTitle">@Model.Title</div>
    <div>@Model.Description</div>
</div>

AspNetViewsCodeReuseExamples/Views/DisplayEditorTemplates/DisplayTemplates/SpecialMovie.cshtml
@model AspNetViewsCodeReuseExamples.IdmbComponent.Movie

<div class="movieContainer specialMovie">
    <div class="movieTitle">@Model.Title</div>
    <div>@Model.Description</div>
</div>

AspNetViewsCodeReuseExamples/Views/DisplayEditorTemplates/EditorTemplates.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.DisplayEditorTemplatesViewModel

<h1>Editor templates examples</h1>

@using (Html.BeginForm())
{
    <h2>Editor template for Boolean</h2>
    @Html.EditorFor(m => m.AreYouOk)

    <h2>Editor template for User class</h2>
    @Html.EditorFor(m => m.User)
    
    <h2>Local default editor template for Movie class</h2>
    @Html.EditorFor(m => m.Movie)

    
    <h2>Local not default editor template for Movie class</h2>
    @Html.EditorFor(m => m.SpecialMovie, "SpecialMovie")
    
    <div>
        <input type="submit" name="Save" value="Save" />
    </div>
}

AspNetViewsCodeReuseExamples/Views/Home/ChildActionItSelf.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.SearchMovieResultsViewModel

<h2>Search result for query: "@Model.Query "</h2>

@if (string.IsNullOrWhiteSpace(Model.Query) || Model.Movies == null || !Model.Movies.Any())
{
    <span>No results</span>
}
else
{
    <ul>
        @foreach (var movie in Model.Movies)
        {
            <li>@movie.Title - @movie.Description</li>
        }
    </ul>
}

AspNetViewsCodeReuseExamples/Views/Home/HtmlHelper.cshtml
@using AspNetViewsCodeReuseExamples.Helpers

@model AspNetViewsCodeReuseExamples.ViewModels.HtmlHelperViewModel

<h1>HTML Helper Example</h1>

<h2>Build-in helpers</h2>
@using (Html.BeginForm())
{
    @Html.Label("Name ");
    @Html.TextBox("name");
}

<h2>User HTML Helper as extension method</h2>
@Html.UnorderedList(Model.Planets)

<h2>User HTML Helper as static method</h2>
@CopyrightsHelper.Copyrights("2014", "Krzysztof Szabelski")

AspNetViewsCodeReuseExamples/Views/Home/Index.cshtml
@model dynamic

<h1>Code Reuse in ASP.NET Views - Examples</h1>

AspNetViewsCodeReuseExamples/Views/Home/PartialViews.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.PartialViewsViewModel

<h1>Partial Views</h1>

@if (Model.IsSpecialUser)
{
    Html.RenderPartial("../Shared/SpecialUser", Model.User);
}
else
{
    @Html.DisplayFor(m => m.User);
}

AspNetViewsCodeReuseExamples/Views/Home/RazorHelpers.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.RazorHelpersViewModel

@helper DisplayTextOrAlternative(string text, string alternative)
{
    if (string.IsNullOrEmpty(text))
    {
        <text>@alternative</text>
    }
    else
    {
        <text>@text</text>
    }
}

<h1>Razor helpers</h1>

<h2>Local helper</h2>
<table>
    <tr>
        <td>Name</td><td>Surname</td><td>Birthday</td>
    </tr>
    
    @foreach (var user in Model.Users)
    {
        <tr>
            <td>@DisplayTextOrAlternative(user.Name, "--Name missing--")</td>
            <td>@DisplayTextOrAlternative(user.Surname, "-- Surname missing--")</td>
            <td>@user.Birthday.ToShortDateString()</td>
        </tr>
        
    }
</table>

<h2>Global helper</h2>

<span>This is normal text | </span>@RazorHelpers.GrowOnHover("but comes from special helper, so hover it!")

AspNetViewsCodeReuseExamples/Views/HtmlHelper/Index.cshtml
@using AspNetViewsCodeReuseExamples.Helpers
@model AspNetViewsCodeReuseExamples.ViewModels.HtmlHelperViewModel

<h1>HTML Helper Example</h1>

<h2>Build-in helpers</h2>
@using (Html.BeginForm())
{
    @Html.Label("Name ")
    @Html.TextBox("name")
}

<h2>User HTML Helper as extension method</h2>
@Html.UnorderedList(Model.Planets)

<h2>User HTML Helper as static method</h2>
@CopyrightsHelper.Copyrights("2014", "Krzysztof Szabelski")

AspNetViewsCodeReuseExamples/Views/PartialViews/Index.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.PartialViewsViewModel

<h1>Partial Views</h1>

@if (Model.IsSpecialUser)
{
    @Html.Partial("../Shared/SpecialUser", Model.User)
}
else
{
    @Html.DisplayFor(m => m.User)
}

AspNetViewsCodeReuseExamples/Views/RazorHelpers/Index.cshtml
@model AspNetViewsCodeReuseExamples.ViewModels.RazorHelpersViewModel

@helper DisplayTextOrAlternative(string text, string alternative)
{
    if (string.IsNullOrEmpty(text))
    {
        <text>@alternative</text>
    }
    else
    {
        <text>@text</text>
    }
}

<h1>Razor helpers</h1>

<h2>Local helper</h2>
<table>
    <tr>
        <td>Name</td>
        <td>Surname</td>
        <td>Birthday</td>
    </tr>

    @foreach (var user in Model.Users)
    {
        <tr>
            <td>@DisplayTextOrAlternative(user.Name, "--Name missing--")</td>
            <td>@DisplayTextOrAlternative(user.Surname, "-- Surname missing--")</td>
            <td>@user.Birthday.ToShortDateString()</td>
        </tr>

    }
</table>

<h2>Global helper</h2>

<span>This is normal text | </span>@RazorHelpers.GrowOnHover("but comes from special helper, so hover it!")

AspNetViewsCodeReuseExamples/Views/Shared/DisplayTemplates/Boolean.cshtml
@model Boolean

<span>
    <input type="radio" name="yesNo" disabled value="true" @( Model ? "checked" : "")>Yes&nbsp;
    <input type="radio" name="yesNo" disabled value="false" @( !Model ? "checked" : "")>No
</span>

AspNetViewsCodeReuseExamples/Views/Shared/DisplayTemplates/User.cshtml
@model AspNetViewsCodeReuseExamples.Models.User

<table class="userDisplay">
    <tbody>
        <tr><td>Name</td><td>@Model.Name</td></tr>
        <tr><td>Surname</td><td>@Model.Surname</td></tr>
        <tr><td>Birthday</td><td>@Model.Birthday.ToShortDateString()</td></tr>
    </tbody>
</table>

AspNetViewsCodeReuseExamples/Views/Shared/EditorTemplates/Boolean.cshtml
@model Boolean

@{
    // Give input name of matching model field, otherwise it cannot be matched with this model when sending response from form.
    // http://stackoverflow.com/questions/6615541/how-to-get-models-field-name-in-custom-editor-template
    var modelFieldName = ViewData.TemplateInfo.HtmlFieldPrefix;
}

<span>
    <input type="radio" name="@modelFieldName" value="true" @( Model ? "checked" : "")>Yes&nbsp;
    <input type="radio" name="@modelFieldName" value="false" @( !Model ? "checked" : "")>No
</span>

AspNetViewsCodeReuseExamples/Views/Shared/EditorTemplates/User.cshtml
@model AspNetViewsCodeReuseExamples.Models.User

<table class="userDisplay">
    <tbody>
        <tr><td>Name</td><td>@Html.TextBoxFor(m => m.Name)</td></tr>
        <tr><td>Surname</td><td>@Html.TextBoxFor(m => m.Surname)</td></tr>
        <tr><td>Birthday</td><td>@Html.TextBoxFor(m => m.Birthday)</td></tr>
    </tbody>
</table>

AspNetViewsCodeReuseExamples/Views/Shared/Navigation.cshtml
<ul>
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("HTML Helper examples", "Index", "HtmlHelper")</li>
    <li>@Html.ActionLink("Display Templates examples", "DisplayTemplates", "DisplayEditorTemplates")</li>
    <li>@Html.ActionLink("Editor Templates examples", "EditorTemplates", "DisplayEditorTemplates")</li>
    <li>@Html.ActionLink("Razor Helpers examples", "Index", "RazorHelpers")</li>
    <li>@Html.ActionLink("Partial Views example", "Index", "PartialViews")</li>
    <li>@Html.ActionLink("Child Action example", "Index", "ChildAction")</li>
    <li>@Html.ActionLink("Different layout example", "Index", "Layouts")</li>
    <li>@Html.ActionLink("Nested layout example", "Nested", "Layouts")</li>
</ul>

AspNetViewsCodeReuseExamples/Views/Shared/SpecialUser.cshtml
@model AspNetViewsCodeReuseExamples.Models.User

<table class="userDisplay">
    <tbody>
        <tr><td>Name</td><td class="specialUser">!!! @Model.Name !!!</td></tr>
        <tr><td>Surname</td><td class="specialUser">!!! @Model.Surname !!!</td></tr>
        <tr><td>Birthday</td><td class="specialUser">@Model.Birthday.ToShortDateString()</td></tr>
    </tbody>
</table>

AspNetViewsCodeReuseExamples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Code Reuse in ASP.NET Views - Examples</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="row">
        <div class="col-md-3 text-right">
            <nav>
                @Html.Partial("Navigation")
            </nav>
        </div>

        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>

AspNetViewsCodeReuseExamples/Views/Shared/_LayoutColorful.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Code Reuse in ASP.NET Views - Examples</title>
    @Styles.Render("~/Content/css")
</head>
<body class="colorfulBody">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="flatNavigation topBar">
                <nav>
                    @Html.Partial("Navigation")
                </nav>
                <div class="clear"></div>
            </div>
            <div class="content">
                @RenderBody()
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</body>
</html>

AspNetViewsCodeReuseExamples/Views/Shared/_LayoutNested.cshtml
@{
    Layout = "_Layout.cshtml";
}

<h1>Nested layout example</h1>

<div>
    @RenderBody()
</div>